apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-alpha-01
commonLabels:
  env: alpha
  productgroup: demo
  

resources:
- ../../../../base/apps/demo-app
- demo-ingress.yaml
patchesStrategicMerge:
- demo-app-volume-patch.yaml
- demo-resource-limits-patch.yaml

images:
  - name: demo-app
    newName: kiranprasadr/images
    newTag: v1.22102025


configMapGenerator:
#demo-app configmaps
- name: demo-app
  literals:
  - TZ="Asia/Calcutta"

- name: demo-app-config
  files:
  - demo-app-configs/index.xml
  - demo-app-configs/photo.jpg
  - demo-app-configs/Resume.pdf
