apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-alpha-01

resources:
  - ../../base/apps/demo-app
  - demo-ingress.yaml

patchesStrategicMerge:
  - demo-resource-limits-patch.yaml

images:
  - name: demo-app
    newName: kiranprasad26/portfolio
    newTag: "23112025"

configMapGenerator:
  - name: demo-app-config
    files:
      - demo-app-configs/index.html
      - demo-app-configs/photo.jpg
      - demo-app-configs/Resume.pdf
